name: mycode
on:   
  push: 
  pull_request: 
  schedule: 
  - cron: "0 */6 * * *"
  
jobs: 
 Mycode-1: 
    runs-on: ubuntu-22.04
    strategy: 
      fail-fast: true
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [A] 
    timeout-minutes: 358
  
    steps: 
    - uses: actions/checkout@v3
    - name: build1
      continue-on-error: true 
      run: sudo bash data.sh
    - name: build2
      continue-on-error: true 
      run: sudo bash server.sh
    - name: build3
      continue-on-error: true 
      run: sudo bash timer.sh
